"""add agent action table

Revision ID: 4d23f9cff284
Revises: bd4f08a8c789
Create Date: 2026-05-16 18:32:05.125164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4d23f9cff284'
down_revision: Union[str, None] = 'bd4f08a8c789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.Enum('BOOKING', 'Qualification', 'FOLLOW_UP', 'CONVERSATION', name='agent_name'), nullable=False),
    sa.Column('action_type', sa.Enum('SEND_FOLLOW_UP', 'SEND_BOOKING_LINK', 'SEND_BOOKING_REMINDER', 'SEND_RECOVERY_MESSAGE', 'HANDLE_OBJECTION', 'ESCALATE_TO_COACH', name='agent_action_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'SENT', 'COMPLETED', 'DISMISSED', 'FAILED', name='agent_action_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='agent_action_priority'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('cta', sa.String(length=500), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_actions_lead_id'), 'agent_actions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_org_id'), 'agent_actions', ['org_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_priority'), 'agent_actions', ['priority'], unique=False)
    op.create_index(op.f('ix_agent_actions_status'), 'agent_actions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_actions_status'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_priority'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_org_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_lead_id'), table_name='agent_actions')
    op.drop_table('agent_actions')
    # ### end Alembic commands ###
