"""add lead state fields

Revision ID: 4d6f19f546d3
Revises: b55d9afd1203
Create Date: 2026-04-25 17:07:36.118737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4d6f19f546d3'
down_revision: Union[str, None] = 'b55d9afd1203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('coach_notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('booking_status', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'last_activity_at')
    op.drop_column('leads', 'booking_status')
    op.drop_column('leads', 'coach_notes')
    # ### end Alembic commands ###
