"""add lead memory table

Revision ID: 54ada19f7112
Revises: 80ec8194617f
Create Date: 2026-04-29 23:01:53.880616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '54ada19f7112'
down_revision: Union[str, None] = '80ec8194617f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('memory_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_memory_lead_id'), 'lead_memory', ['lead_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_memory_lead_id'), table_name='lead_memory')
    op.drop_table('lead_memory')
    # ### end Alembic commands ###
