"""Add email and sender settings

Revision ID: 6222bf426768
Revises: 4d23f9cff284
Create Date: 2026-06-01 21:23:02.239711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6222bf426768'
down_revision: Union[str, None] = '4d23f9cff284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('opt_out', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('organizations', sa.Column('sender_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'sender_settings')
    op.drop_column('leads', 'opt_out')
    op.drop_column('leads', 'email')
    # ### end Alembic commands ###
