"""create initial tables

Revision ID: b55d9afd1203
Revises: 
Create Date: 2026-04-18 17:22:35.000469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b55d9afd1203'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_summary', sa.Text(), nullable=True),
    sa.Column('client_type', sa.String(length=120), nullable=False),
    sa.Column('revenue_stage', sa.String(length=120), nullable=False),
    sa.Column('lead_source', sa.String(length=120), nullable=False),
    sa.Column('lead_temperature', sa.String(length=50), nullable=False),
    sa.Column('problem_mentioned', sa.Text(), nullable=False),
    sa.Column('coach_offer_price_range', sa.String(length=120), nullable=False),
    sa.Column('offer_type', sa.String(length=120), nullable=False),
    sa.Column('call_goal', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ANALYZED', 'QUALIFIED', 'NURTURE', 'BOOKED', 'CLOSED_WON', 'CLOSED_LOST', name='lead_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_client_name'), 'leads', ['client_name'], unique=False)
    op.create_index(op.f('ix_leads_website_url'), 'leads', ['website_url'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('intelligence_score', sa.Integer(), nullable=False),
    sa.Column('full_report_json', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_lead_id'), 'reports', ['lead_id'], unique=False)
    op.create_table('qualifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('fit_score', sa.Integer(), nullable=False),
    sa.Column('urgency_score', sa.Integer(), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('recommended_action', sa.Enum('BOOK_CALL', 'FOLLOW_UP', 'NURTURE', 'DISQUALIFY', name='recommended_action'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualifications_lead_id'), 'qualifications', ['lead_id'], unique=False)
    op.create_index(op.f('ix_qualifications_report_id'), 'qualifications', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualifications_report_id'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_lead_id'), table_name='qualifications')
    op.drop_table('qualifications')
    op.drop_index(op.f('ix_reports_lead_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_leads_website_url'), table_name='leads')
    op.drop_index(op.f('ix_leads_client_name'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
