"""add_users_organizations_org_id_to_leads

Revision ID: bd4f08a8c789
Revises: 54ada19f7112
Create Date: 2026-05-12 22:31:12.926358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd4f08a8c789'
down_revision: Union[str, None] = '54ada19f7112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('leads', sa.Column('org_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_leads_org_id'), 'leads', ['org_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_org_id'), table_name='leads')
    op.drop_column('leads', 'org_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
