"""Add brand_voice to Organization

Revision ID: bd5bc54aba78
Revises: 6222bf426768
Create Date: 2026-06-06 13:25:50.841753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd5bc54aba78'
down_revision: Union[str, None] = '6222bf426768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('brand_voice', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'brand_voice')
    # ### end Alembic commands ###
